### ISSUE TITLE
Unable to recrypt files, check that input and output files are clear and arguments are coool

### ISSUE THREAD

**Issue by visheshCuriousDev** [jsreport/jsreport-pdf-password#3]
The following error while generating reports using jsreport-pdf-password, do you know why this occurs ?

`2018-07-19T04:53:10.142Z - info: Starting rendering request 7 (user: null) requestId=7
2018-07-19T04:53:10.142Z - info: Rendering anonymous template { recipe:phantom-pdf,engine:handlebars} requestId=7
2018-07-19T04:53:10.143Z - info: Rendering anonymous template { recipe:phantom-pdf,engine:handlebars} requestId=7
2018-07-19T04:53:10.143Z - debug: Inline data specified. requestId=7
2018-07-19T04:53:10.143Z - debug: Inline data specified. requestId=7
2018-07-19T04:53:10.145Z - debug: Resources not defined for this template. requestId=7
2018-07-19T04:53:10.145Z - debug: Resources not defined for this template. requestId=7
2018-07-19T04:53:10.146Z - debug: Base url not specified, skipping its injection. requestId=7
2018-07-19T04:53:10.146Z - debug: Base url not specified, skipping its injection. requestId=7
2018-07-19T04:53:10.147Z - debug: Rendering engine handlebars requestId=7
2018-07-19T04:53:10.319Z - debug: Compiled template not found in the cache, compiling timestamp=Thu Jul 19 2018 10:23:10 GMT+0530 (IST), requestId=7
2018-07-19T04:53:10.321Z - debug: Replaced images [] requestId=7
2018-07-19T04:53:10.321Z - debug: Replaced images [] requestId=7
2018-07-19T04:53:10.323Z - debug: Executing recipe phantom-pdf requestId=7
2018-07-19T04:53:10.323Z - debug: Starting child request to render pdf header requestId=7
2018-07-19T04:53:10.324Z - info: Starting rendering request 8 (user: null) requestId=8
2018-07-19T04:53:10.324Z - info: Rendering anonymous template { recipe:html,engine:handlebars} requestId=8
2018-07-19T04:53:10.325Z - info: Rendering anonymous template { recipe:html,engine:handlebars} requestId=8
2018-07-19T04:53:10.325Z - debug: Inline data specified. requestId=8
2018-07-19T04:53:10.325Z - debug: Inline data specified. requestId=8
2018-07-19T04:53:10.326Z - debug: Resources not defined for this template. requestId=8
2018-07-19T04:53:10.326Z - debug: Resources not defined for this template. requestId=8
2018-07-19T04:53:10.326Z - debug: Base url not specified, skipping its injection. requestId=8
2018-07-19T04:53:10.326Z - debug: Base url not specified, skipping its injection. requestId=8
2018-07-19T04:53:10.327Z - debug: Rendering engine handlebars requestId=8
2018-07-19T04:53:10.449Z - debug: Compiled template not found in the cache, compiling timestamp=Thu Jul 19 2018 10:23:10 GMT+0530 (IST), requestId=8
2018-07-19T04:53:10.450Z - debug: Replaced images [] requestId=8
2018-07-19T04:53:10.451Z - debug: Replaced images [] requestId=8
2018-07-19T04:53:10.451Z - debug: Executing recipe html requestId=8
2018-07-19T04:53:10.452Z - debug: Skipping storing report. requestId=8
2018-07-19T04:53:10.452Z - debug: Skipping storing report. requestId=8
2018-07-19T04:53:10.453Z - info: Rendering request 8 finished in 129 ms requestId=8
2018-07-19T04:53:10.453Z - debug: Starting child request to render pdf footer requestId=7
2018-07-19T04:53:10.454Z - info: Starting rendering request 9 (user: null) requestId=9
2018-07-19T04:53:10.454Z - info: Rendering anonymous template { recipe:html,engine:handlebars} requestId=9
2018-07-19T04:53:10.454Z - info: Rendering anonymous template { recipe:html,engine:handlebars} requestId=9
2018-07-19T04:53:10.455Z - debug: Inline data specified. requestId=9
2018-07-19T04:53:10.455Z - debug: Inline data specified. requestId=9
2018-07-19T04:53:10.456Z - debug: Resources not defined for this template. requestId=9
2018-07-19T04:53:10.457Z - debug: Resources not defined for this template. requestId=9
2018-07-19T04:53:10.457Z - debug: Base url not specified, skipping its injection. requestId=9
2018-07-19T04:53:10.457Z - debug: Base url not specified, skipping its injection. requestId=9
2018-07-19T04:53:10.458Z - debug: Rendering engine handlebars requestId=9
2018-07-19T04:53:10.580Z - debug: Compiled template not found in the cache, compiling timestamp=Thu Jul 19 2018 10:23:10 GMT+0530 (IST), requestId=9
2018-07-19T04:53:10.580Z - debug: Replaced images [] requestId=9
2018-07-19T04:53:10.581Z - debug: Replaced images [] requestId=9
2018-07-19T04:53:10.581Z - debug: Executing recipe html requestId=9
2018-07-19T04:53:10.582Z - debug: Skipping storing report. requestId=9
2018-07-19T04:53:10.582Z - debug: Skipping storing report. requestId=9
2018-07-19T04:53:10.582Z - info: Rendering request 9 finished in 128 ms requestId=9
2018-07-19T04:53:12.574Z - debug: Converting in dedicated phantomjs 1.9.8 timestamp=Thu Jul 19 2018 10:23:10 GMT+0530 (IST), requestId=7
2018-07-19T04:53:12.574Z - debug: Request file:///%2Ftmp%2Fjsreport%2Fa2bc7470-8b0f-11e8-820d-1ba7c4fb16bahtml.html timestamp=Thu Jul 19 2018 10:23:10 GMT+0530 (IST), requestId=7
2018-07-19T04:53:12.574Z - debug: Request http://localhost:4000/fonts.css timestamp=Thu Jul 19 2018 10:23:10 GMT+0530 (IST), requestId=7
2018-07-19T04:53:12.574Z - debug: Request http://localhost:4000/chart.js timestamp=Thu Jul 19 2018 10:23:10 GMT+0530 (IST), requestId=7
2018-07-19T04:53:12.574Z - debug: Request http://s3.ap-south-1.amazonaws.com/dv-release-testing/partner/logo/ibm-ionixx_logo.png timestamp=Thu Jul 19 2018 10:23:10 GMT+0530 (IST), requestId=7
2018-07-19T04:53:12.574Z - debug: Request http://www.google.co.in/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0ahUKEwjzmLvKgu7WAhXJLI8KHQsZAeUQjRwIBw&url=http%3A%2F%2Fwww.slate.com%2Fblogs%2Ffuture_tense%2F2015%2F09%2F01%2Fgoogle_s_new_animated_logo_is_the_future_of_mobile_branding.html&psig=AOvVaw2oIMfRjePmlCCNIDLIgBiH&ust=1507998568108869 timestamp=Thu Jul 19 2018 10:23:10 GMT+0530 (IST), requestId=7
2018-07-19T04:53:12.574Z - debug: Request http://s3.ap-south-1.amazonaws.com/digiverifier-testing/partner/logo/digiverifierlogo_logo_vector_final.png timestamp=Thu Jul 19 2018 10:23:11 GMT+0530 (IST), requestId=7
2018-07-19T04:53:12.574Z - debug: PhantomJS printing done timestamp=Thu Jul 19 2018 10:23:11 GMT+0530 (IST), requestId=7
2018-07-19T04:53:12.575Z - debug: PhantomJS printing done timestamp=Thu Jul 19 2018 10:23:11 GMT+0530 (IST), requestId=7
2018-07-19T04:53:12.575Z - debug: PhantomJS printing done timestamp=Thu Jul 19 2018 10:23:11 GMT+0530 (IST), requestId=7
2018-07-19T04:53:12.575Z - debug: PhantomJS printing done timestamp=Thu Jul 19 2018 10:23:11 GMT+0530 (IST), requestId=7
2018-07-19T04:53:12.575Z - debug: PhantomJS printing done timestamp=Thu Jul 19 2018 10:23:11 GMT+0530 (IST), requestId=7
2018-07-19T04:53:12.575Z - debug: PhantomJS printing done timestamp=Thu Jul 19 2018 10:23:11 GMT+0530 (IST), requestId=7
2018-07-19T04:53:12.575Z - debug: PhantomJS printing done timestamp=Thu Jul 19 2018 10:23:12 GMT+0530 (IST), requestId=7
2018-07-19T04:53:12.575Z - debug: PhantomJS printing done timestamp=Thu Jul 19 2018 10:23:12 GMT+0530 (IST), requestId=7
2018-07-19T04:53:12.576Z - debug: PhantomJS printing done timestamp=Thu Jul 19 2018 10:23:12 GMT+0530 (IST), requestId=7
2018-07-19T04:53:12.576Z - debug: Request http://intruct-javascript-ending/ timestamp=Thu Jul 19 2018 10:23:12 GMT+0530 (IST), requestId=7
2018-07-19T04:53:12.576Z - warn: Unable to load resource (#7URL:http://intruct-javascript-ending/) timestamp=Thu Jul 19 2018 10:23:12 GMT+0530 (IST), requestId=7
2018-07-19T04:53:12.577Z - warn: Error code: 3. Description: Host intruct-javascript-ending not found timestamp=Thu Jul 19 2018 10:23:12 GMT+0530 (IST), requestId=7
2018-07-19T04:53:12.577Z - debug: PhantomJS printing done timestamp=Thu Jul 19 2018 10:23:12 GMT+0530 (IST), requestId=7
2018-07-19T04:53:12.577Z - debug: phantom-pdf recipe finished with 7 pages generated requestId=7
2018-07-19T04:53:12.580Z - debug: pdf-password starting to add password to PDF file requestId=7
2018-07-19T04:53:12.589Z - debug: pdf-password finished adding password to PDF file requestId=7
2018-07-19T04:53:12.589Z - debug: pdf-password starting to add password to PDF file requestId=7
2018-07-19T04:53:12.597Z - error: Error when processing render request Error during rendering report: Unable to recrypt files, check that input and output files are clear and arguments are coool TypeError: Unable to recrypt files, check that input and output files are clear and arguments are coool
    at /home/ionixx/NetBeansProjects/crossbow/node_modules/jsreport-pdf-password/lib/pdfPassword.js:93:12
    at tryCatcher (/home/ionixx/NetBeansProjects/crossbow/node_modules/jsreport-pdf-password/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ionixx/NetBeansProjects/crossbow/node_modules/jsreport-pdf-password/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/ionixx/NetBeansProjects/crossbow/node_modules/jsreport-pdf-password/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/ionixx/NetBeansProjects/crossbow/node_modules/jsreport-pdf-password/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/ionixx/NetBeansProjects/crossbow/node_modules/jsreport-pdf-password/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/home/ionixx/NetBeansProjects/crossbow/node_modules/jsreport-pdf-password/node_modules/bluebird/js/release/promise.js:636:18)
    at /home/ionixx/NetBeansProjects/crossbow/node_modules/jsreport-pdf-password/node_modules/bluebird/js/release/nodeback.js:42:21
    at /home/ionixx/NetBeansProjects/crossbow/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15) requestId=7
`

**Comment by bjrmatos** [comment]
in cases like this, it depends on what is the pdf produced, it can be that the [internal library](https://github.com/galkahana/HummusJS) that we use it's having a problem with the produced pdf. in any case we need the full case (how your template looks like) to be able to replicate the issue

**Comment by LubomirIgonda1** [comment]
@bjrmatos Hi I have the same issue here is my env:

    win 10 build 19041.508
    node: 12.18.3
    "jsreport-assets": "1.6.0",
    "jsreport-chrome-pdf": "1.8.0",
    "jsreport-core": "2.9.0",
    "jsreport-ejs": "2.2.0",
    "jsreport-pdf-password": "2.3.0",
    "jsreport-pdf-utils": "1.8.0"

my code 
    
    const jsConfig = {
		template: {
			engine: 'ejs',
			recipe: 'chrome-pdf',
			content: 'template',
			pdfPassword: {
				active: true,
				password: '123'
			}
		}
	}

	const instance: jsreport.Reporter = await jsreportInstance
	return instance.render(jsConfig)

screenshot temp folder 

![image](https://user-images.githubusercontent.com/9303146/95864538-cc935e00-0d65-11eb-811c-7e0f786396fc.png)

I tried to open the file from temp folder and it works perfectly

If you need more information just let me know.

**Comment by bjrmatos** [comment]
@LubomirIgonda1 can you try the pdf [password using pdf-utils](https://jsreport.net/learn/pdf-utils#password-protection)? all our efforts now are moved to the pdf password implementation in pdf-utils, this extension was difficult to maintain and the [internal lib](https://github.com/galkahana/HummusJS) that does the pdf encryption is not maintained anymore, so please try the pdf-utils password and if you have the issue open a new issue in the pdf-utils or jsreport repository.
